"""FastAPI bridge exposing the career/academic orchestrator to the React dashboard.

This is the first HTTP entrypoint for the project — no web framework existed
before this file (pyproject.toml had no FastAPI/Flask/uvicorn), so FastAPI was
added as a new dependency. Covers all four feature runners (GAP, FIT, SHIFT,
PROFESSOR_COMMENTS) — each route is a thin wrapper around run_feature().

Student identity here is the dashboard "slug" (e.g. "jordanReyes"), matching
frontend/src/data/dataAdapter.ts's `/data/student_${slug}.json` convention —
not the numeric `student.id` inside the JSON, which has no filesystem mapping.
"""

import json
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from CampusIQ_career.ai.errors import AIConfigError
from CampusIQ_career.ai.openrouter_client import (
    DEEPSEEK_R1_REASONING_TIMEOUT_SECONDS,
    OpenRouterClient,
)
from CampusIQ_career.features.base import FeatureResult
from CampusIQ_career.features.orchestrator import run_feature

load_dotenv()

STUDENTS_DIR = Path(__file__).resolve().parents[1] / "data" / "students"
# Pre-generated by CampusIQ_career/demo/build_demo_cache.py -- same convention
# the frontend already fetches directly (frontend/src/data/dataAdapter.ts).
CACHED_ANALYSIS_DIR = Path(__file__).resolve().parents[1] / "frontend" / "public" / "data"

app = FastAPI(title="Campus IQ AI Bridge")

# Dev-only: Vite runs on a different origin than uvicorn. Tighten this before
# any real deployment — "*" is fine for a local demo, not for production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def load_student_profile(student_slug: str) -> dict:
    path = STUDENTS_DIR / f"student_{student_slug}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Unknown student '{student_slug}'.")
    return json.loads(path.read_text(encoding="utf-8"))


def build_client() -> OpenRouterClient:
    try:
        return OpenRouterClient(timeout=DEEPSEEK_R1_REASONING_TIMEOUT_SECONDS)
    except AIConfigError as exc:
        # Surface as a FeatureResult-shaped failure so the frontend's single
        # "failed" branch handles both "AI call failed" and "server misconfigured"
        # without needing a second error shape.
        raise HTTPException(status_code=503, detail=str(exc)) from exc


def load_cached_feature_result(student_slug: str, feature_name: str) -> dict | None:
    """Look up a pre-generated result for one feature, or None if unavailable.

    Cache files are built by CampusIQ_career/demo/build_demo_cache.py, which
    only writes FIT/GAP/SHIFT (PROFESSOR_COMMENTS is never included) -- so a
    None return for that feature is expected, not a bug. The returned dict may
    itself have status="failed" baked in (build_demo_cache.py writes whatever
    run_career_analysis() produced, including failures) -- callers must check
    status before treating this as a good result.
    """
    cache_path = CACHED_ANALYSIS_DIR / f"analysis_{student_slug}.json"
    if not cache_path.exists():
        return None
    try:
        cached = json.loads(cache_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return cached.get("results", {}).get(feature_name)


def run_feature_with_fallback(feature_name: str, student_slug: str, profile: dict, client: OpenRouterClient) -> dict:
    """Run a live feature call; on failure, silently serve a cached success.

    The dashboard should render a cached *successful* result exactly as if it
    were live -- no error or banner. A cache entry that is itself
    status="failed" (or missing/has an unrecognized status -- schema drift)
    must not be served as a success; fail closed and return an explicit
    failure instead, reusing the cached failure's own summary/errors when
    available so the message still reflects what actually went wrong. If no
    cached entry exists at all, the live failure result is returned as-is
    (unhandled genuine-failure case; see Fix 2 write-up for what's flagged
    there).
    """
    result = run_feature(feature_name, profile, client)
    if result.get("status") != "failed":
        return result

    cached = load_cached_feature_result(student_slug, feature_name)
    if cached is None:
        return result
    if cached.get("status") == "success":
        return cached

    return FeatureResult(
        feature=feature_name,
        status="failed",
        summary=cached.get("summary") or result.get("summary", f"{feature_name} analysis failed."),
        data={},
        errors=cached.get("errors") or result.get("errors", []),
    ).to_dict()


@app.post("/api/students/{student_slug}/analyze/gap")
def analyze_gap(student_slug: str) -> dict:
    profile = load_student_profile(student_slug)
    client = build_client()
    return run_feature_with_fallback("GAP", student_slug, profile, client)


@app.post("/api/students/{student_slug}/analyze/fit")
def analyze_fit(student_slug: str) -> dict:
    profile = load_student_profile(student_slug)
    client = build_client()
    return run_feature_with_fallback("FIT", student_slug, profile, client)


@app.post("/api/students/{student_slug}/analyze/shift")
def analyze_shift(student_slug: str) -> dict:
    profile = load_student_profile(student_slug)
    client = build_client()
    return run_feature_with_fallback("SHIFT", student_slug, profile, client)


@app.post("/api/students/{student_slug}/analyze/professor-comments")
def analyze_professor_comments(student_slug: str) -> dict:
    profile = load_student_profile(student_slug)
    client = build_client()
    return run_feature_with_fallback("PROFESSOR_COMMENTS", student_slug, profile, client)
