"""FastAPI bridge exposing the career/academic orchestrator to the React dashboard.

This is the first HTTP entrypoint for the project — no web framework existed
before this file (pyproject.toml had no FastAPI/Flask/uvicorn), so FastAPI was
added as a new dependency. Covers all four feature runners (GAP, FIT, SHIFT,
PROFESSOR_COMMENTS) — each route is a thin wrapper around run_feature().

Student identity here is the dashboard "slug" (e.g. "jordanReyes"), matching
frontend/src/data/dataAdapter.ts's `/data/student_${slug}.json` convention —
not the numeric `student.id` inside the JSON, which has no filesystem mapping.
"""

import hmac
import json
import os
import threading
import time
from collections import deque
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

from dotenv import load_dotenv
from fastapi import APIRouter, Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware

from CampusIQ_career.ai.errors import AIConfigError
from CampusIQ_career.ai.openrouter_client import (
    DEEPSEEK_R1_REASONING_TIMEOUT_SECONDS,
    OpenRouterClient,
)
from CampusIQ_career.features.base import FeatureResult
from CampusIQ_career.features.orchestrator import run_feature

load_dotenv()

STUDENTS_DIR = Path(__file__).resolve().parents[1] / "data" / "students"
# Pre-generated by CampusIQ_career/demo/build_demo_cache.py -- same convention
# the frontend already fetches directly (frontend/src/data/dataAdapter.ts).
CACHED_ANALYSIS_DIR = Path(__file__).resolve().parents[1] / "frontend" / "public" / "data"
PROXY_SECRET_HEADER = "X-CampusIQ-Proxy-Secret"


def _positive_int_env(name: str, default: int, maximum: int) -> int:
    try:
        value = int(os.getenv(name, str(default)))
    except ValueError:
        return default
    return value if 1 <= value <= maximum else default


def _positive_float_env(name: str, default: float, maximum: float) -> float:
    try:
        value = float(os.getenv(name, str(default)))
    except ValueError:
        return default
    return value if 0 < value <= maximum else default


def _allowed_origins_from_env() -> tuple[str, ...]:
    configured = os.getenv("CAMPUSIQ_ALLOWED_ORIGINS", "")
    return tuple(
        origin
        for raw in configured.split(",")
        if (origin := raw.strip()) and origin != "*"
    )


@dataclass(frozen=True)
class APIConfig:
    proxy_secret: str
    allowed_origins: tuple[str, ...]
    rate_limit_requests: int
    rate_limit_window_seconds: float
    max_concurrent_ai_requests: int

    @classmethod
    def from_env(cls) -> "APIConfig":
        return cls(
            proxy_secret=os.getenv("CAMPUSIQ_PROXY_SECRET", "").strip(),
            allowed_origins=_allowed_origins_from_env(),
            rate_limit_requests=_positive_int_env("CAMPUSIQ_RATE_LIMIT_REQUESTS", 10, 10_000),
            rate_limit_window_seconds=_positive_float_env(
                "CAMPUSIQ_RATE_LIMIT_WINDOW_SECONDS", 60.0, 86_400.0
            ),
            max_concurrent_ai_requests=_positive_int_env(
                "CAMPUSIQ_MAX_CONCURRENT_AI_REQUESTS", 2, 100
            ),
        )


class SlidingWindowRateLimiter:
    """Bounded, process-local limiter shared by trusted proxy requests."""

    def __init__(self, limit: int, window_seconds: float) -> None:
        self.limit = limit
        self.window_seconds = window_seconds
        self._requests: deque[float] = deque(maxlen=limit)
        self._lock = threading.Lock()

    def allow(self, *, now: float | None = None) -> bool:
        timestamp = time.monotonic() if now is None else now
        cutoff = timestamp - self.window_seconds
        with self._lock:
            while self._requests and self._requests[0] <= cutoff:
                self._requests.popleft()
            if len(self._requests) >= self.limit:
                return False
            self._requests.append(timestamp)
            return True


class AIConcurrencyGate:
    """Nonblocking, process-local capacity guard for expensive live AI work."""

    def __init__(self, capacity: int) -> None:
        self._semaphore = threading.BoundedSemaphore(capacity)

    @contextmanager
    def slot(self) -> Iterator[None]:
        if not self._semaphore.acquire(blocking=False):
            raise HTTPException(status_code=429, detail="AI service is busy; retry later.")
        try:
            yield
        finally:
            self._semaphore.release()


def authorize_proxy_request(request: Request) -> None:
    config: APIConfig = request.app.state.api_config
    if not config.proxy_secret:
        raise HTTPException(status_code=503, detail="Backend proxy authentication is not configured.")

    provided = request.headers.get(PROXY_SECRET_HEADER, "")
    if not provided or not hmac.compare_digest(
        provided.encode("utf-8"), config.proxy_secret.encode("utf-8")
    ):
        raise HTTPException(status_code=401, detail="Unauthorized.")

    if not request.app.state.rate_limiter.allow():
        raise HTTPException(status_code=429, detail="Request rate limit exceeded.")

router = APIRouter()


def load_student_profile(student_slug: str) -> dict:
    path = STUDENTS_DIR / f"student_{student_slug}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Unknown student '{student_slug}'.")
    return json.loads(path.read_text(encoding="utf-8"))


def build_client() -> OpenRouterClient:
    try:
        return OpenRouterClient(timeout=DEEPSEEK_R1_REASONING_TIMEOUT_SECONDS)
    except AIConfigError as exc:
        # Surface as a FeatureResult-shaped failure so the frontend's single
        # "failed" branch handles both "AI call failed" and "server misconfigured"
        # without needing a second error shape.
        raise HTTPException(status_code=503, detail=str(exc)) from exc


def load_cached_feature_result(student_slug: str, feature_name: str) -> dict | None:
    """Look up a pre-generated result for one feature, or None if unavailable.

    Cache files are built by CampusIQ_career/demo/build_demo_cache.py, which
    only writes FIT/GAP/SHIFT (PROFESSOR_COMMENTS is never included) -- so a
    None return for that feature is expected, not a bug. The returned dict may
    itself have status="failed" baked in (build_demo_cache.py writes whatever
    run_career_analysis() produced, including failures) -- callers must check
    status before treating this as a good result.
    """
    cache_path = CACHED_ANALYSIS_DIR / f"analysis_{student_slug}.json"
    if not cache_path.exists():
        return None
    try:
        cached = json.loads(cache_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return cached.get("results", {}).get(feature_name)


def run_feature_with_fallback(feature_name: str, student_slug: str, profile: dict, client: OpenRouterClient) -> dict:
    """Run a live feature call; on failure, silently serve a cached success.

    The dashboard should render a cached *successful* result exactly as if it
    were live -- no error or banner. A cache entry that is itself
    status="failed" (or missing/has an unrecognized status -- schema drift)
    must not be served as a success; fail closed and return an explicit
    failure instead, reusing the cached failure's own summary/errors when
    available so the message still reflects what actually went wrong. If no
    cached entry exists at all, the live failure result is returned as-is
    (unhandled genuine-failure case; see Fix 2 write-up for what's flagged
    there).
    """
    result = run_feature(feature_name, profile, client)
    if result.get("status") != "failed":
        return result

    cached = load_cached_feature_result(student_slug, feature_name)
    if cached is None:
        return result
    if cached.get("status") == "success":
        return cached

    return FeatureResult(
        feature=feature_name,
        status="failed",
        summary=cached.get("summary") or result.get("summary", f"{feature_name} analysis failed."),
        data={},
        errors=cached.get("errors") or result.get("errors", []),
    ).to_dict()


def _run_protected_feature(request: Request, feature_name: str, student_slug: str) -> dict:
    profile = load_student_profile(student_slug)
    try:
        with request.app.state.ai_concurrency.slot():
            client = build_client()
            return run_feature_with_fallback(feature_name, student_slug, profile, client)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=502, detail="Analysis service is unavailable.") from exc


@router.get("/health")
def health() -> dict:
    return {"status": "ok"}


@router.post("/api/students/{student_slug}/analyze/gap", dependencies=[Depends(authorize_proxy_request)])
def analyze_gap(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "GAP", student_slug)


@router.post("/api/students/{student_slug}/analyze/fit", dependencies=[Depends(authorize_proxy_request)])
def analyze_fit(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "FIT", student_slug)


@router.post("/api/students/{student_slug}/analyze/shift", dependencies=[Depends(authorize_proxy_request)])
def analyze_shift(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "SHIFT", student_slug)


@router.post(
    "/api/students/{student_slug}/analyze/professor-comments",
    dependencies=[Depends(authorize_proxy_request)],
)
def analyze_professor_comments(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "PROFESSOR_COMMENTS", student_slug)


def create_app(config: APIConfig | None = None) -> FastAPI:
    active_config = config or APIConfig.from_env()
    application = FastAPI(title="Campus IQ AI Bridge")
    application.state.api_config = active_config
    application.state.rate_limiter = SlidingWindowRateLimiter(
        active_config.rate_limit_requests, active_config.rate_limit_window_seconds
    )
    application.state.ai_concurrency = AIConcurrencyGate(active_config.max_concurrent_ai_requests)
    application.add_middleware(
        CORSMiddleware,
        allow_origins=list(active_config.allowed_origins),
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Content-Type", PROXY_SECRET_HEADER],
    )
    application.include_router(router)
    return application


app = create_app()
