"""FastAPI bridge exposing the career/academic orchestrator to the React dashboard.

This is the first HTTP entrypoint for the project — no web framework existed
before this file (pyproject.toml had no FastAPI/Flask/uvicorn), so FastAPI was
added as a new dependency. Covers all four feature runners (GAP, FIT, SHIFT,
PROFESSOR_COMMENTS) — each route is a thin wrapper around run_feature().

Student identity here is the dashboard "slug" (e.g. "jordanReyes"), matching
frontend/src/data/dataAdapter.ts's `/data/student_${slug}.json` convention —
not the numeric `student.id` inside the JSON, which has no filesystem mapping.
"""

import hmac
import json
import os
import threading
import time
from collections import deque
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator
from pydantic import BaseModel

from dotenv import load_dotenv
from fastapi import APIRouter, Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware

from CampusIQ_career.academics.gpa import CourseRecord, GradeMapRow, Institution, compute_both
from CampusIQ_career.ai.errors import AIConfigError
from CampusIQ_career.ai.openrouter_client import (
    DEEPSEEK_R1_REASONING_TIMEOUT_SECONDS,
    OpenRouterClient,
)
from CampusIQ_career.features.base import FeatureResult
from CampusIQ_career.features.orchestrator import RUNNERS, run_feature
from CampusIQ_career.supabase_client import SupabaseConfigError, build_client_for_token


load_dotenv()

STUDENTS_DIR = Path(__file__).resolve().parents[1] / "data" / "students"
# Pre-generated by CampusIQ_career/demo/build_demo_cache.py -- same convention
# the frontend already fetches directly (frontend/src/data/dataAdapter.ts).
CACHED_ANALYSIS_DIR = Path(__file__).resolve().parents[1] / "frontend" / "public" / "data"
PROXY_SECRET_HEADER = "X-CampusIQ-Proxy-Secret"

# These five are fabricated demo fixtures whose full records are already served
# unauthenticated from frontend/public/data/. They are exempt from bearer-token
# authorization because that data is public by design. Every other slug requires
# an authenticated session. This list lives in code rather than an env var so it
# cannot be misconfigured in production to allowlist a real student.
#
# Derived from the actual filenames in data/students/ (student_<slug>.json).
DEMO_STUDENT_SLUGS = frozenset(
    {
        "ethanBrooks",
        "jordanReyes",
        "marcusWebb",
        "priyaNair",
        "sofiaRamirez",
    }
)


def _positive_int_env(name: str, default: int, maximum: int) -> int:
    try:
        value = int(os.getenv(name, str(default)))
    except ValueError:
        return default
    return value if 1 <= value <= maximum else default


def _positive_float_env(name: str, default: float, maximum: float) -> float:
    try:
        value = float(os.getenv(name, str(default)))
    except ValueError:
        return default
    return value if 0 < value <= maximum else default


def _allowed_origins_from_env() -> tuple[str, ...]:
    configured = os.getenv("CAMPUSIQ_ALLOWED_ORIGINS", "")
    return tuple(
        origin
        for raw in configured.split(",")
        if (origin := raw.strip()) and origin != "*"
    )


@dataclass(frozen=True)
class APIConfig:
    proxy_secret: str
    allowed_origins: tuple[str, ...]
    rate_limit_requests: int
    rate_limit_window_seconds: float
    max_concurrent_ai_requests: int

    @classmethod
    def from_env(cls) -> "APIConfig":
        return cls(
            proxy_secret=os.getenv("CAMPUSIQ_PROXY_SECRET", "").strip(),
            allowed_origins=_allowed_origins_from_env(),
            rate_limit_requests=_positive_int_env("CAMPUSIQ_RATE_LIMIT_REQUESTS", 10, 10_000),
            rate_limit_window_seconds=_positive_float_env(
                "CAMPUSIQ_RATE_LIMIT_WINDOW_SECONDS", 60.0, 86_400.0
            ),
            max_concurrent_ai_requests=_positive_int_env(
                "CAMPUSIQ_MAX_CONCURRENT_AI_REQUESTS", 2, 100
            ),
        )


class SlidingWindowRateLimiter:
    """Bounded, process-local limiter shared by trusted proxy requests."""

    def __init__(self, limit: int, window_seconds: float) -> None:
        self.limit = limit
        self.window_seconds = window_seconds
        self._requests: deque[float] = deque(maxlen=limit)
        self._lock = threading.Lock()

    def allow(self, *, now: float | None = None) -> bool:
        timestamp = time.monotonic() if now is None else now
        cutoff = timestamp - self.window_seconds
        with self._lock:
            while self._requests and self._requests[0] <= cutoff:
                self._requests.popleft()
            if len(self._requests) >= self.limit:
                return False
            self._requests.append(timestamp)
            return True


class AIConcurrencyGate:
    """Nonblocking, process-local capacity guard for expensive live AI work."""

    def __init__(self, capacity: int) -> None:
        self._semaphore = threading.BoundedSemaphore(capacity)

    @contextmanager
    def slot(self) -> Iterator[None]:
        if not self._semaphore.acquire(blocking=False):
            raise HTTPException(status_code=429, detail="AI service is busy; retry later.")
        try:
            yield
        finally:
            self._semaphore.release()


def authorize_proxy_request(request: Request) -> None:
    config: APIConfig = request.app.state.api_config
    if not config.proxy_secret:
        raise HTTPException(status_code=503, detail="Backend proxy authentication is not configured.")

    provided = request.headers.get(PROXY_SECRET_HEADER, "")
    if not provided or not hmac.compare_digest(
        provided.encode("utf-8"), config.proxy_secret.encode("utf-8")
    ):
        raise HTTPException(status_code=401, detail="Unauthorized.")

    if not request.app.state.rate_limiter.allow():
        raise HTTPException(status_code=429, detail="Request rate limit exceeded.")


def authorize_student_access(request: Request, student_slug: str) -> None:
    """Deny-by-default check that the caller may read `student_slug`'s record.

    This is a separate control from authorize_proxy_request: that one proves the
    request came through our own proxy, this one proves the *caller* is entitled
    to this particular student. The proxy attaches its shared secret to every
    request it forwards and authenticates nobody, so without this check any
    anonymous caller could name any slug.

    Demo fixtures short-circuit (their records are public by design; see
    DEMO_STUDENT_SLUGS). Every other slug requires a session bearer token, and
    is then denied: `students` has no slug column, so there is no way to map a
    session to a dashboard slug. Rather than invent a mapping, this fails closed
    with 403.

    Never reads SUPABASE_SECRET_KEY -- build_client_for_token uses the anon
    publishable key plus the caller's own token, so RLS applies as that user.
    Its appearance anywhere in this path would be a bug.

    Forward-references _bearer_token_from_request, defined lower in this module
    alongside the v2 route it was written for; both are resolved at call time.
    """
    if student_slug in DEMO_STUDENT_SLUGS:
        return

    token = _bearer_token_from_request(request)

    try:
        client = build_client_for_token(token)
    except SupabaseConfigError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    # Same sequence the v2 GPA route uses: no filter and no identifier from the
    # request -- RLS narrows `students` to the row owned by this token.
    try:
        student_rows = client.table("students").select("*").execute().data
    except Exception as exc:  # noqa: BLE001 -- an unverifiable session is denied
        # Fails closed: a rejected/expired token and a transient backend error
        # are indistinguishable here, and 401 is the safe direction for an
        # authorization gate.
        raise HTTPException(status_code=401, detail="Could not verify session.") from exc

    if not student_rows:
        raise HTTPException(status_code=404, detail="No student profile visible for this session.")

    raise HTTPException(
        status_code=403,
        detail=(
            "Cannot verify ownership of this student record: the students table has "
            "no slug column, so an authenticated session cannot be mapped to a "
            "dashboard slug. Only demo fixtures are servable by these routes."
        ),
    )

router = APIRouter()


def load_student_profile(student_slug: str) -> dict:
    if not student_slug.isalnum() or len(student_slug) > 64:
        raise HTTPException(status_code=404, detail=f"Unknown student '{student_slug}'.")
    path = STUDENTS_DIR / f"student_{student_slug}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Unknown student '{student_slug}'.")
    return json.loads(path.read_text(encoding="utf-8"))


def build_client() -> OpenRouterClient:
    try:
        return OpenRouterClient(timeout=DEEPSEEK_R1_REASONING_TIMEOUT_SECONDS)
    except AIConfigError as exc:
        # Surface as a FeatureResult-shaped failure so the frontend's single
        # "failed" branch handles both "AI call failed" and "server misconfigured"
        # without needing a second error shape.
        raise HTTPException(status_code=503, detail=str(exc)) from exc


def _matches_contract(value: object, contract: object) -> bool:
    if isinstance(contract, dict):
        return isinstance(value, dict) and all(
            key in value and _matches_contract(value[key], expected)
            for key, expected in contract.items()
        )
    if isinstance(contract, list):
        if not isinstance(value, list):
            return False
        return not contract or all(_matches_contract(item, contract[0]) for item in value)
    if isinstance(contract, int):
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if isinstance(contract, str):
        return isinstance(value, str)
    return False


def _valid_cached_feature_result(feature_name: str, result: object) -> bool:
    runner = RUNNERS.get(feature_name)
    if runner is None or not isinstance(result, dict):
        return False
    return (
        result.get("feature") == feature_name
        and result.get("status") == "success"
        and isinstance(result.get("summary"), str)
        and result.get("errors") == []
        and _matches_contract(result.get("data"), runner.output_contract)
    )


def load_cached_feature_result(
    student_slug: str, feature_name: str, expected_student_id: object | None = None
) -> dict | None:
    """Return a schema-compatible successful result for this student/feature.

    Cache files are built by CampusIQ_career/demo/build_demo_cache.py. A
    feature only has a cache entry if that build run included it (via
    --feature) for this student, so a None return simply means that
    combination hasn't been cached -- it is looked up generically here rather
    than assuming a fixed set of features. Malformed files, student-ID or
    feature mismatches, failed entries, nonempty errors, and stale data shapes
    are cache misses rather than trusted responses.
    """
    if not student_slug.isalnum() or len(student_slug) > 64 or feature_name not in RUNNERS:
        return None
    cache_path = CACHED_ANALYSIS_DIR / f"analysis_{student_slug}.json"
    if not cache_path.exists():
        return None
    try:
        cached = json.loads(cache_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(cached, dict):
        return None
    if expected_student_id is not None and str(cached.get("student_id")) != str(expected_student_id):
        return None
    results = cached.get("results")
    if not isinstance(results, dict):
        return None
    result = results.get(feature_name)
    return result if _valid_cached_feature_result(feature_name, result) else None


def run_feature_with_fallback(feature_name: str, student_slug: str, profile: dict, client: OpenRouterClient) -> dict:
    """Run a live feature call; on failure, silently serve a cached success.

    The dashboard should render a cached *successful* result exactly as if it
    were live -- no error or banner. A cache entry that is itself
    status="failed" (or missing/has an unrecognized status -- schema drift)
    must not be served as a success; fail closed and return an explicit
    failure instead, reusing the cached failure's own summary/errors when
    available so the message still reflects what actually went wrong. If no
    cached entry exists at all, the live failure result is returned as-is
    (unhandled genuine-failure case; see Fix 2 write-up for what's flagged
    there).
    """
    result = run_feature(feature_name, profile, client)
    if result.get("status") != "failed":
        return result

    student_id = profile.get("student", {}).get("id")
    cached = load_cached_feature_result(student_slug, feature_name, student_id)
    if cached is None:
        return result
    if cached.get("status") == "success":
        return cached

    return FeatureResult(
        feature=feature_name,
        status="failed",
        summary=cached.get("summary") or result.get("summary", f"{feature_name} analysis failed."),
        data={},
        errors=cached.get("errors") or result.get("errors", []),
    ).to_dict()


def _run_protected_feature(request: Request, feature_name: str, student_slug: str) -> dict:
    """Serve a validated cache hit, otherwise run live work within capacity."""
    authorize_student_access(request, student_slug)
    profile = load_student_profile(student_slug)
    student_id = profile.get("student", {}).get("id")
    cached = load_cached_feature_result(student_slug, feature_name, student_id)
    if cached is not None:
        return cached
    try:
        with request.app.state.ai_concurrency.slot():
            client = build_client()
            return run_feature_with_fallback(feature_name, student_slug, profile, client)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=502, detail="Analysis service is unavailable.") from exc


@router.get("/health")
def health() -> dict:
    return {"status": "ok"}


@router.post("/api/students/{student_slug}/analyze/gap", dependencies=[Depends(authorize_proxy_request)])
def analyze_gap(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "GAP", student_slug)


@router.post("/api/students/{student_slug}/analyze/fit", dependencies=[Depends(authorize_proxy_request)])
def analyze_fit(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "FIT", student_slug)


@router.post("/api/students/{student_slug}/analyze/shift", dependencies=[Depends(authorize_proxy_request)])
def analyze_shift(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "SHIFT", student_slug)


@router.post(
    "/api/students/{student_slug}/analyze/professor-comments",
    dependencies=[Depends(authorize_proxy_request)],
)
def analyze_professor_comments(request: Request, student_slug: str) -> dict:
    return _run_protected_feature(request, "PROFESSOR_COMMENTS", student_slug)

# ── Chat: conversational advisor grounded in the full student record ─────────

MAX_CHAT_HISTORY = 12 
CHAT_CONTEXT_FEATURES = ("GAP", "FIT", "SHIFT")


class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    message: str
    history: list[ChatMessage] = []


def load_analysis_bundle(student_slug: str) -> dict:
    """Best-effort cached FIT/GAP/SHIFT results, for chat context only."""
    if not student_slug.isalnum() or len(student_slug) > 64:
        return {}
    path = CACHED_ANALYSIS_DIR / f"analysis_{student_slug}.json"
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    results = data.get("results") if isinstance(data, dict) else None
    if not isinstance(results, dict):
        return {}
    return {k: results[k] for k in CHAT_CONTEXT_FEATURES if k in results}


def build_chat_messages(profile: dict, analysis: dict, body: ChatRequest) -> list[dict]:
    name = profile.get("student", {}).get("name", "the student")
    system = (
        f"You are Campus IQ, a warm, concise academic and career advisor speaking directly "
        f"with {name}. You have their full academic and career profile plus prior FIT/GAP/SHIFT "
        "analysis. Answer specifically using that data — cite concrete courses, grades, target "
        "roles, skills, or gaps when relevant. If something is not in the data, say so rather "
        "than inventing it. Keep replies short, direct, and encouraging.\n\n"
        f"STUDENT PROFILE (JSON):\n{json.dumps(profile, sort_keys=True)}\n\n"
        f"PRIOR ANALYSIS (FIT/GAP/SHIFT JSON):\n{json.dumps(analysis, sort_keys=True)}"
    )
    messages = [{"role": "system", "content": system}]
    for turn in body.history[-MAX_CHAT_HISTORY:]:
        role = turn.role if turn.role in ("user", "assistant") else "user"
        if isinstance(turn.content, str) and turn.content.strip():
            messages.append({"role": role, "content": turn.content})
    messages.append({"role": "user", "content": body.message})
    return messages


@router.post("/api/students/{student_slug}/chat", dependencies=[Depends(authorize_proxy_request)])
def chat(request: Request, student_slug: str, body: ChatRequest) -> dict:
    authorize_student_access(request, student_slug)
    if not body.message or not body.message.strip():
        raise HTTPException(status_code=400, detail="Message is required.")
    profile = load_student_profile(student_slug)
    analysis = load_analysis_bundle(student_slug)
    messages = build_chat_messages(profile, analysis, body)
    try:
        client = build_client()
        response = client.complete(messages=messages, role="chat", model="@preset/chat")
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001 — surface any live failure uniformly
        raise HTTPException(status_code=502, detail="Chat service is unavailable.") from exc
    return {"reply": response.text, "model": response.model}


# ── v2: Supabase-backed GPA endpoint ──────────────────────────────────────────
# Auth here is the student's own bearer token (Supabase session JWT), not the
# X-CampusIQ-Proxy-Secret shared secret used by the /api/students/* routes
# above -- authorize_proxy_request does not apply to this route.

BEARER_PREFIX = "Bearer "


def _bearer_token_from_request(request: Request) -> str:
    header = request.headers.get("Authorization", "")
    if not header.startswith(BEARER_PREFIX):
        raise HTTPException(status_code=401, detail="Missing or malformed Authorization header.")
    token = header[len(BEARER_PREFIX):].strip()
    if not token:
        raise HTTPException(status_code=401, detail="Missing or malformed Authorization header.")
    return token


@router.get("/api/v2/student/me/gpa")
def get_student_gpa(request: Request) -> dict:
    token = _bearer_token_from_request(request)
    client = build_client_for_token(token)

    student_rows = client.table("students").select("*").execute().data
    if not student_rows:
        raise HTTPException(status_code=404, detail="No student profile visible for this session.")
    student_id = student_rows[0]["id"]

    home_rows = (
        client.table("student_institutions")
        .select("institution_id")
        .eq("student_id", student_id)
        .eq("relationship", "home")
        .execute()
        .data
    )
    if not home_rows:
        raise HTTPException(status_code=409, detail="Student has no home institution on record.")
    home_institution_id = home_rows[0]["institution_id"]

    institution_rows = (
        client.table("institutions").select("*").eq("id", home_institution_id).execute().data
    )
    if not institution_rows:
        raise HTTPException(
            status_code=409, detail="Home institution row could not be resolved."
        )
    institution_row = institution_rows[0]

    grade_map_rows = (
        client.table("grade_point_map")
        .select("*")
        .eq("institution_id", home_institution_id)
        .execute()
        .data
    )
    grade_map = {
        row["letter"]: GradeMapRow(
            letter=row["letter"],
            points=row["points"],
            counts_toward_gpa=row["counts_toward_gpa"],
            counts_toward_credit=row["counts_toward_credit"],
        )
        for row in grade_map_rows
    }

    course_rows = (
        client.table("course_records").select("*").eq("student_id", student_id).execute().data
    )
    records = [
        CourseRecord(
            course_code=row["course_code"],
            credit_hours=float(row["credit_hours"]),
            letter_grade=row["letter_grade"],
            credit_type=row["credit_type"],
            status=row["status"],
            institution_id=row["institution_id"],
            confirmed_at=row.get("confirmed_at"),
        )
        for row in course_rows
    ]

    institution = Institution(
        id=institution_row["id"],
        name=institution_row["name"],
        uses_plus_minus=institution_row["uses_plus_minus"],
        transfer_grades_count_toward_gpa=institution_row["transfer_grades_count_toward_gpa"],
    )

    both = compute_both(records, institution, grade_map)

    # projected's excluded set is the meaningful one to surface: official
    # mode excludes nearly every in-progress course purely on status scope,
    # which isn't a data problem worth reporting -- projected only excludes
    # a course for a substantive reason (unmapped grade, transfer not
    # counted, unconfirmed, etc).
    excluded = [
        {"course_code": record.course_code, "reason": reason}
        for record, reason in both.projected.excluded
    ]

    return {
        "institution": {
            "id": institution_row["id"],
            "name": institution_row["name"],
            "uses_plus_minus": institution_row["uses_plus_minus"],
        },
        "official": both.official.gpa,
        "projected": both.projected.gpa,
        "completed_hours": both.completed_hours,
        "in_progress_hours": both.in_progress_hours,
        "earned_hours": both.official.earned_hours,
        "excluded": excluded,
    }


def create_app(config: APIConfig | None = None) -> FastAPI:
    active_config = config or APIConfig.from_env()
    application = FastAPI(
        title="Campus IQ AI Bridge",
        docs_url=None,
        redoc_url=None,
        openapi_url=None,
    )
    application.state.api_config = active_config
    application.state.rate_limiter = SlidingWindowRateLimiter(
        active_config.rate_limit_requests, active_config.rate_limit_window_seconds
    )
    application.state.ai_concurrency = AIConcurrencyGate(active_config.max_concurrent_ai_requests)
    application.add_middleware(
        CORSMiddleware,
        allow_origins=list(active_config.allowed_origins),
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Content-Type", PROXY_SECRET_HEADER],
    )
    application.include_router(router)
    return application


app = create_app()
