"""Career market-intelligence provider for GAP (and, later, FIT/SHIFT).

The GAP prompt expects an O*NET-scored "market requirements" block per target
role so it can distinguish must-have vs. nice-to-have gaps. Target roles map
to SOC codes via the curated lookup in ``data/role_requirements.json`` (exact
role-string match, no guessing), and the SOC codes key into importance-scored
O*NET requirements.

This reads a static data file housed in the repo
(``data/reference/onet_soc_requirements.json``), generated by
``data/onet/build_onet.py`` from an O*NET tabular release. Do not hand-edit it;
re-run the loader. It covers all 1,016 occupations in the release, so a SOC
code missing from it is a bad mapping rather than a coverage gap.

DFW posting data is NOT coming. The ATS fetcher that would have supplied it is
closed (see ``data/onet/STATUS.md``), so this module deliberately exposes no
postings key -- an always-None field would just invite the prompt to imply
posting evidence it does not have.

This module is dependency-free (stdlib only) and never raises into the runner:
if the data file is missing or a role can't be mapped, it returns a structured
block with a note so GAP still runs (just less grounded).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Mapping, Sequence


# repo root = .../GradusIQ_career/features/market_data.py -> parents[2]
_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_DATA_PATH = _REPO_ROOT / "data" / "reference" / "onet_soc_requirements.json"

# Env override lets the demo/cache runner point at a different data file.
_DATA_PATH = Path(os.getenv("GRADUSIQ_ONET_DATA", str(_DEFAULT_DATA_PATH)))

# Fallback if the data file omits its own threshold.
_DEFAULT_MUST_HAVE_THRESHOLD = 70

# Curated role -> SOC lookup, shared with role_requirements_for() in gap.py.
# Each of the 14 demo target roles has a hand-assigned, correct SOC code here.
# Loaded independently (not imported from gap.py) to keep this module
# dependency-free of the runners.
_ROLE_REQUIREMENTS_PATH = _REPO_ROOT / "data" / "role_requirements.json"

_role_soc_cache: Mapping[str, str] | None = None
# Parsed O*NET catalog, populated on first successful load. See _load_onet.
_onet_cache: Mapping[str, Any] | None = None


def _load_role_soc_map() -> Mapping[str, str]:
    """Load {target_role: soc_code} from the curated role_requirements.json.

    Cached at module scope (not functools.lru_cache — a plain dict swap is
    enough here and keeps this testable via monkeypatching _DATA_PATH-style
    globals without cache-clearing gymnastics).
    """
    global _role_soc_cache
    if _role_soc_cache is not None:
        return _role_soc_cache
    try:
        with _ROLE_REQUIREMENTS_PATH.open("r", encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        _role_soc_cache = {}
        return _role_soc_cache
    if not isinstance(data, Mapping):
        _role_soc_cache = {}
        return _role_soc_cache
    _role_soc_cache = {
        role: entry["soc_code"]
        for role, entry in data.items()
        if not role.startswith("_")
        and isinstance(entry, Mapping)
        and isinstance(entry.get("soc_code"), str)
        and entry["soc_code"]
    }
    return _role_soc_cache


def _load_onet() -> Mapping[str, Any]:
    """Load the static O*NET requirements file; return {} on any problem.

    Cached at module scope, the same way and for the same reasons as
    _load_role_soc_map above -- a plain global swap rather than
    functools.lru_cache, so a test can repoint _DATA_PATH and clear
    _onet_cache without cache-clearing gymnastics.

    THE CACHE IS NOT AN OPTIMIZATION DETAIL HERE. This file grew from 31KB to
    5.5MB when the O*NET reference expanded to all 1,016 occupations, and every
    provider entry point calls this: get_market_requirements, get_shift_signals,
    and resolve_soc's callers. Uncached, a single GAP or FIT run reparsed ~5.5MB
    several times over -- measured at ~20ms and a full transient allocation per
    parse, on a per-request path.

    A FAILED load is deliberately NOT cached. The empty dict is returned but
    _onet_cache stays None, so a transient read error (a partially written file
    during a deploy, say) does not pin an empty catalog into the process for its
    entire lifetime -- which would silently degrade every downstream role to
    provenance "none" with no way back short of a restart.
    """
    global _onet_cache
    if _onet_cache is not None:
        return _onet_cache
    try:
        with _DATA_PATH.open("r", encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return {}
    if not isinstance(data, Mapping):
        return {}
    _onet_cache = data
    return _onet_cache


def resolve_soc(target_role: str) -> str | None:
    """Look up one target role's curated SOC code from role_requirements.json.

    This used to keyword-match target-role text against a hardcoded SOC map,
    which could produce confidently wrong matches (e.g. "Business Analyst
    Intern" resolving to 15-1211.00 Computer Systems Analysts instead of the
    correct 13-1111.00 Management Analysts) and covered fewer roles than the
    hand-curated lookup already maintained in role_requirements.json. Exact
    match only, by design — an unrecognized role returns None rather than a
    guessed code.
    """
    if not isinstance(target_role, str):
        return None
    return _load_role_soc_map().get(target_role)


def _nearest_rated_neighbour(
    entry: Mapping[str, Any], catalog: Mapping[str, Any]
) -> tuple[dict[str, str], Mapping[str, Any]] | None:
    """Find the closest related occupation O*NET HAS rated, or None.

    O*NET has never surveyed 122 of its 1,016 occupations, and 29 of those have
    at least one rated occupation in their Primary-Short related list -- which
    is ordered by O*NET's own relatedness index, so the first rated hit is the
    closest available match rather than an arbitrary one.

    Borrowing beats live web research for these: it is instant, free, and
    traceable to a named occupation the student can look up. The condition is
    disclosure -- these are a NEIGHBOURING occupation's scores, and presenting
    them as the target role's own would be a quiet misattribution. The caller
    records the source in ``borrowed_from`` and the prompt is required to say so.

    Returns (source_descriptor, that occupation's entry).
    """
    for neighbour in entry.get("related") or []:
        if not isinstance(neighbour, Mapping):
            continue
        candidate = catalog.get(neighbour.get("soc"))
        if isinstance(candidate, Mapping) and candidate.get("skills"):
            return (
                {"soc": neighbour.get("soc"), "title": candidate.get("title")},
                candidate,
            )
    return None


def get_market_requirements(target_roles: Sequence[str] | None) -> dict[str, Any]:
    """Build the market-requirements block injected into the GAP context.

    Shape (stable — export/cache can rely on it):
        {
          "source": "onet_static" | "none",
          "must_have_threshold": int,        # importance >= this => must-have
          "by_role": {                       # one entry per target role
             "<role text>": {
                 "soc_code": "17-2011.00" | None,
                 "soc_title": str | None,
                 "job_zone": int | None,
                 "requirements": {"skills": [...], "knowledge": [...], "abilities": [...]},
                 "hot_software": [str, ...],  # O*NET Hot Technology products
                 "provenance": "onet" | "none",
                 "matched": bool,
             }, ...
          },
          "notes": [str, ...],
        }

    ``provenance`` is what tells the prompt whether a gap was scored against
    real importance data. This module only ever emits "onet" or "none" — it
    knows nothing about the research agent. ``gap.py`` upgrades "none" to
    "agent" for the roles it backfills.

    ``matched`` means "has usable ratings", NOT "the SOC exists". The reference
    file carries an entry for every occupation in the release, including the
    122 O*NET has never surveyed, so key existence stopped being a useful
    signal the moment the catalog went from 10 occupations to 1,016.
    """
    roles = [r for r in (target_roles or []) if isinstance(r, str) and r.strip()]
    onet = _load_onet()
    catalog = onet.get("roles", {}) if isinstance(onet, Mapping) else {}
    threshold = int(onet.get("must_have_threshold", _DEFAULT_MUST_HAVE_THRESHOLD)) \
        if isinstance(onet, Mapping) else _DEFAULT_MUST_HAVE_THRESHOLD

    notes: list[str] = []
    if not catalog:
        notes.append(
            "O*NET requirements file unavailable or empty; GAP is running "
            "without market grounding. Populate data/reference/onet_soc_requirements.json."
        )
    if onet.get("_placeholder"):
        notes.append(
            "O*NET values are PLACEHOLDER. Replace with real importance scores "
            "from the June handoff doc before treating gap severity as authoritative."
        )

    by_role: dict[str, Any] = {}
    for role in roles:
        soc = resolve_soc(role)
        entry = catalog.get(soc) if soc else None
        if not isinstance(entry, Mapping):
            entry = {}
        skills = entry.get("skills") or []
        # Present in the release is not the same as usable: O*NET has never
        # surveyed 122 of the 1,016 occupations, and those still get an entry
        # (with empty lists) so callers can tell "no ratings exist" apart from
        # "this SOC is wrong". Only usable ratings count as matched.
        rated = bool(skills)

        # Borrow ONLY the ratings. Title, job zone and software stay the target
        # occupation's own -- Finance Intern has 33 hot technologies of its own
        # despite having no ratings, and swapping the whole entry would discard
        # real data in favour of a neighbour's.
        ratings = entry
        borrowed_from = None
        if not rated and entry:
            neighbour = _nearest_rated_neighbour(entry, catalog)
            if neighbour is not None:
                borrowed_from, ratings = neighbour
                skills = ratings.get("skills") or []
                rated = bool(skills)

        if borrowed_from:
            notes.append(
                f"O*NET has not rated SOC {soc} ('{role}'). Its requirements are "
                f"borrowed from the closest related occupation O*NET has rated: "
                f"{borrowed_from['soc']} {borrowed_from['title']}. This must be "
                "disclosed to the student, not presented as the role's own data."
            )
        elif not soc:
            notes.append(
                f"Role '{role}' has no curated SOC code in role_requirements.json; "
                "add one there to enable O*NET grounding for it."
            )
        elif catalog and not entry:
            # Guarded on `catalog` because when the file is missing entirely,
            # every role looks unmapped. The file-level note above is the real
            # explanation; blaming the mapping here would send someone editing
            # role_requirements.json for nothing.
            notes.append(
                f"Role '{role}' maps to SOC {soc}, which is not in the O*NET release - "
                "the mapping in role_requirements.json is stale or wrong."
            )
        elif catalog and not rated:
            notes.append(
                f"O*NET has no ratings for SOC {soc} ('{role}'). Requirements must come "
                "from the research agent and must not be presented as O*NET-scored."
            )

        by_role[role] = {
            "soc_code": soc,
            "soc_title": entry.get("title"),
            "job_zone": entry.get("job_zone"),
            "requirements": {
                "skills": skills,
                "knowledge": ratings.get("knowledge") or [],
                "abilities": ratings.get("abilities") or [],
            },
            "hot_software": entry.get("hot_software") or [],
            "in_demand_software": entry.get("in_demand_software") or [],
            "provenance": ("onet_neighbor" if borrowed_from else "onet") if rated else "none",
            "borrowed_from": borrowed_from,
            "matched": rated,
        }

    return {
        "source": "onet_static" if catalog else "none",
        "must_have_threshold": threshold,
        "by_role": by_role,
        "notes": notes,
    }


# How many core tasks to carry per role. O*NET ships a median of 15; SHIFT
# turns them into 3-5 durable_skills entries, so the full list is more context
# than the output can use and crowds out the trend signal.
_MAX_CORE_TASKS = 8


def get_shift_signals(target_roles: Sequence[str] | None) -> dict[str, Any]:
    """Build the local O*NET grounding block injected into the SHIFT context.

    SHIFT had no external data at all: every role-specific claim was model
    recall. Three of its five output fields can be grounded from data already
    on disk, at no latency cost:

        adjacent_paths[]      <- related       (5 Primary-Short occupations)
        ai_fluency_guidance[] <- hot_software  (O*NET Hot Technology products)
        durable_skills[]      <- core_tasks    (what the job actually does)

    The other two (task_shifts, role_evolution_summary) are about what is
    changing right now, which no annual survey answers -- those come from
    role_research_agent.get_role_trends, added to the context by ShiftRunner.

    Shape:
        {
          "source": "onet_static" | "none",
          "by_role": {
             "<role text>": {
                 "soc_code": str | None,
                 "soc_title": str | None,
                 "related": [{"soc": str, "title": str}, ...],
                 "hot_software": [str, ...],
                 "core_tasks": [str, ...],
                 "grounded": bool,
             }, ...
          },
          "notes": [str, ...],
        }
    """
    roles = [r for r in (target_roles or []) if isinstance(r, str) and r.strip()]
    onet = _load_onet()
    catalog = onet.get("roles", {}) if isinstance(onet, Mapping) else {}

    notes: list[str] = []
    if not catalog:
        notes.append(
            "O*NET reference file unavailable or empty; SHIFT has no local grounding "
            "for adjacent paths, tools, or durable tasks."
        )

    by_role: dict[str, Any] = {}
    for role in roles:
        soc = resolve_soc(role)
        entry = catalog.get(soc) if soc else None
        if not isinstance(entry, Mapping):
            entry = {}
        related = entry.get("related") or []
        hot_software = entry.get("hot_software") or []
        core_tasks = (entry.get("core_tasks") or [])[:_MAX_CORE_TASKS]
        # Deliberately NOT keyed off ratings: an occupation with no importance
        # scores can still have tools, tasks and neighbours, and those are what
        # SHIFT actually consumes. Finance Intern is exactly that case.
        grounded = bool(related or hot_software or core_tasks)
        if catalog and soc and not grounded:
            notes.append(
                f"O*NET has no tools, tasks, or related occupations for SOC {soc} "
                f"('{role}'); SHIFT must not invent adjacent paths for it."
            )
        by_role[role] = {
            "soc_code": soc,
            "soc_title": entry.get("title"),
            "related": related,
            "hot_software": hot_software,
            "core_tasks": core_tasks,
            "grounded": grounded,
        }

    return {
        "source": "onet_static" if catalog else "none",
        "by_role": by_role,
        "notes": notes,
    }
